Nullability
PW-MiNI-IO2-2023-Group-6/Specyfikacja pull request #8
Opened 2023-04-27 20:21 UTC by Meeso1

2023-04-27 20:23 UTC, Meeso1 commented on adopterAPI.json
>            },
Do we want `phoneNumber` and `address` to be nullable? It doesn't affect anything, so we really just need to choose what we prefer.

2023-05-09 14:18 UTC, kubaurban requested changes

2023-05-09 14:18 UTC, kubaurban commented on shelterAPI.json
> -            "nullable": true
I think it can stay nullable

2023-05-09 14:18 UTC, kubaurban commented on announcementsAPI.json
> -            "nullable": true
I think we could leave breed nullability at it is

2023-05-09 14:18 UTC, kubaurban commented on announcementsAPI.json
> -            "nullable": true
I think we could leave description nullability at it is

2023-05-09 14:18 UTC, kubaurban commented on announcementsAPI.json
> -            "nullable": true
Same as above

2023-05-09 14:18 UTC, kubaurban commented on announcementsAPI.json
> -            "nullable": true
Same as above

2023-05-09 14:18 UTC, kubaurban commented on announcementsAPI.json
I would make nullable following properties:
- minAge and maxAge in GET /announcements endpoint query parameters

2023-05-16 16:39 UTC, kubaurban approved these changes

2023-05-16 16:51 UTC, merged